provider = spid:test
#stato = ITALIA

##DELEGATO PF
#url = https://cittadini.dev.notifichedigitali.it/
#user = lucrezia
#pwd = password123
#delegato.pf.displayName = Lucrezia Borgia
#delegato.pf.name = Lucrezia
#delegato.pf.familyName = Borgia
#delegato.pf.codiceFiscale =  BRGLRZ80D58H501Q
##delegato.pf.fiscalNumber = TINIT-BRGLRZ80D58H501Q
#delegato.pf.verification.code = 12345

#DELEGATO PG
#delegato.pg.ragioneSociale = Le Epistolae srl
#delegato.pg.displayName = Le Epistolae srl
#delegato.pg.codiceFiscale = LELPTR04A01C352E
delegato.pg.emailPecPG = DanteAlighieri@paradiso.it
#delegato.pg.fiscalNumber = TINIT-LELPTR04A01C352E

#PERSONA FISICA
persona.fisica.email = provaemailpf@test.it
persona.fisica.email1 = prova@test.it
persona.fisica.emailPec = pectest@pec.it
persona.fisica.emailPec1 = prova@pec.it
persona.fisica.additionalEmail = pectest2@pec.it

# PERSONA GIURIDICA
persona.giuridica.email = provaemail@test.it
persona.giuridica.mail = prova@test.it
persona.giuridica.emailPec = pec@pec.pagopa.it
persona.giuridica.pec = prova@pec.it

# PERSONA GIURIDICA_1
persona.giuridica_1.emailPec = DanteAlighieri@paradiso.it

