
# | --------- | --------- | ---------------- | ------------------- |
# | TYPE      | PLATFORM  | ENVIRONMENT      | USER                |
# |-----------|-----------|------------------|---------------------|
# | DELEGANTE | PF        | TEST/DEV         | GAIO GIULIO CESARE  |
pn.external.user.cesare = cesare
pn.external.pwd.cesare = password123
# |-----------|-----------|------------------|---------------------|
# | DELEGATO  | PF        | TEST/DEV         | LUCREZIA BORGIA     |
pn.external.user.lucrezia = lucrezia
pn.external.pwd.lucrezia = password123
# |-----------|-----------|------------------|---------------------|
# | DELEGANTE | PG        | TEST/DEV         | CONVIVIO SPA        |
pn.external.user.dante = DanteAlighieri
pn.external.pwd.dante = test
# |-----------|-----------|------------------|---------------------|
# | DELEGATO  | PG        | TEST/DEV         | LE EPISTOLAE SRL    |
pn.external.user.petrarca = FrancescoPetrarca
pn.external.pwd.petrarca = test
# |-----------|-----------|------------------|---------------------|
# | MITTENTE  | PA        | TEST/DEV         | COMUNE DI VERONA    |
pn.external.user.mittente = albino63
pn.external.pwd.mittente = test
# |-----------|-----------|------------------|----------------------|
pn.external.user.mittenteViggiu = ggiorgi
pn.external.pwd.mittenteViggiu = test


# |----------------------| HELPDESK |----------------------|
pn.external.userDev.helpdesk  = test@test.com
pn.external.pwdDev.helpdesk   = Test_Cognito_1.!
pn.external.userUat.helpdesk  = admin@uat.pagopa.it
pn.external.pwdUat.helpdesk   = Admin-uatcognito1
pn.external.userTest.helpdesk = admin@test.pagopa.it
pn.external.pwdTest.helpdesk  = Admin-testcognito1

